version: "3.9"

services:
  web:
    build: ./estate_project
    #command: python /code/estate_project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/estate_project
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      web_estate_backend_network:
        ipv4_address: '10.7.0.2'
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=estate_db"
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      web_estate_backend_network:
        ipv4_address: '10.7.0.3'

volumes:
  postgres_data:

networks:
  web_estate_backend_network:
    ipam:
      driver: default
      config:
        - subnet: 10.7.0.0/24

