version: "3.9"

services:
  web:
    build: ./estate_project
    #command: python /code/estate_project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/estate_project
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=estate_db"
      - "POSTGRES_HOST=127.0.0.1"
    expose:
      - 5432
    ports:
      - 5432:5432

volumes:
  postgres_data:

