# Generated by Django 4.2.1 on 2023-05-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
