# Generated by Django 4.2.1 on 2023-09-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_backend', '0004_faq_jobvacancy_promocode_employee_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='responsibilities',
            field=models.CharField(default='Sales manager', max_length=255),
        ),
    ]
