# Generated by Django 4.2.1 on 2023-09-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_backend', '0006_post_author_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
